server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food-ordering-db
    username: restaurant_service
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cache:
    type: redis
    cache-names: restaurant, menu
    redis:
      time-to-live: 10m

security:
  jwt:
    issuer: food-ordering
    hs256-secret-base64: ${JWT_HS256_SECRET_BASE64:c2VjcmV0a2V5eXl5eXlheWF5YXlzZHNhamtkaGFzamtsZGZhc2tmZGFza2ZoZHNhamtmaGRhc2prZmRzYWtqZmFkaHNma2pkYXNobGZoZGFzamtmaHNkYWtqZmhkc2prZmFkaHNma2Roc2Fma2poZmprZHNoZmpraHNkZmtqZHNoZmtqZHNoZmprZHNoZmRqa3NoZmprZHNoZmRqa3NmaHNqa2ZoZHNqa2ZoZHNqa2Zoc2Rqa2Zoc2Rqa2ZoZHNqa2ZoZHNqa2Y=}
    expiration: 3600

pii:
  aes:
    key-base64: ${AES_KEY_BASE64:c2VjcmV0eXl5eXl5eXl5dA==}